services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Пробрасываем порт для доступа к приложению
    depends_on:
      db:
        condition: service_healthy # Ждет, пока база будет здорова
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - app_network
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_DATA: /var/lib/postgresql/
    ports:
      - "5436:5432" # Пробрасываем порт для доступа к базе данных
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Проверка здоровья для базы данных
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: always
    

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
